version: '3'

volumes:
  mariadb:
    driver: ${VOLUMES_DRIVER}

networks:
  stack:
    driver: bridge

services:
  workspace:
    image: mbora/mautic_workspace 
    build:
      context: ./workspace
      args: 
        - PHP_VERSION=${PHP_VERSION}
        - PHP_INSTALL_MBSTRING=${PHP_INSTALL_MBSTRING}
        - PHP_INSTALL_SQLITE=${PHP_INSTALL_SQLITE}
        - PHP_INSTALL_XML=${PHP_INSTALL_XML}
        - PHP_INSTALL_ZIP=${PHP_INSTALL_ZIP}
        - PHP_INSTALL_JSON=${PHP_INSTALL_JSON}
        - PHP_INSTALL_CURL=${PHP_INSTALL_CURL}
        - PHP_INSTALL_BCMATH=${PHP_INSTALL_BCMATH}
        - PHP_INSTALL_MYSQLI=${PHP_INSTALL_MYSQLI}
        - PHP_INSTALL_IMAP=${PHP_INSTALL_IMAP}
    depends_on:
      - php-fpm
      - nginx
    volumes:
      - ${APP_CODE_PATH_HOST}:/var/www
    networks:
      - stack
    tty: true

  nginx:
    # image: customimages_nginx
    image: mbora/mautic_nginx
    build:
      context: ./nginx
    depends_on:
      - php-fpm
    ports:
      - "80:80"
    volumes:
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
      - ${APP_CODE_PATH_HOST}:/var/www
    networks:
      - stack
    links:
      - php-fpm

  php-fpm:
    # image: customimages_php-fpm
    image: mbora/mautic_php-fpm
    build:
      context: ./php-fpm
      args:
        - PHP_VERSION=${PHP_VERSION}
        - PHP_INSTALL_ZIP=${PHP_INSTALL_ZIP}
        - PHP_INSTALL_XDEBUG=${PHP_INSTALL_XDEBUG}
        - PHP_INSTALL_BCMATH=${PHP_INSTALL_BCMATH}
        - PHP_INSTALL_MYSQLI=${PHP_INSTALL_MYSQLI}
        - PHP_INSTALL_IMAP=${PHP_INSTALL_IMAP}
    networks:
      - stack
    volumes:
      - ${APP_CODE_PATH_HOST}:/var/www
    extra_hosts:
      - "idehost:${DEBUGGER_HOST_IP}"

  mariadb:
    image: mbora/mautic_mariadb
    build: ./mariadb
    hostname: mariadb
    volumes:
      - ${DATA_PATH_HOST}/mariadb:/var/lib/mysql
    ports:
      - "${MARIADB_PORT}:3306"
    environment:
      - MYSQL_DATABASE=${MARIADB_DATABASE}
      - MYSQL_USER=${MARIADB_USER}
      - MYSQL_PASSWORD=${MARIADB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    networks:
      - stack
