version: '3'

volumes:
  mariadb:
    driver: ${VOLUMES_DRIVER}

networks:
  stack:
    driver: bridge

services:
  workspace:
    build:
      context: ./workspace
    depends_on:
      - php-fpm
      - nginx
    volumes:
      - ${APP_CODE_PATH_HOST}:/var/www
    networks:
      - stack
    tty: true

  nginx:
    # image: customimages_nginx
    image: mbora/mautic_nginx
    build:
      context: ./nginx
    depends_on:
      - php-fpm
    ports:
      - "80:80"
    volumes:
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
      - ${APP_CODE_PATH_HOST}:/var/www
    networks:
      - stack
    links:
      - php-fpm

  php-fpm:
    # image: customimages_php-fpm
    image: mbora/mautic_php-fpm
    build:
      context: ./php-fpm
    networks:
      - stack
    volumes:
      - ${APP_CODE_PATH_HOST}:/var/www

  mariadb:
    build: ./mariadb
    volumes:
      - ${DATA_PATH_HOST}/mariadb:/var/lib/mysql
    ports:
      - "${MARIADB_PORT}:3306"
    environment:
      - MYSQL_DATABASE=${MARIADB_DATABASE}
      - MYSQL_USER=${MARIADB_USER}
      - MYSQL_PASSWORD=${MARIADB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    networks:
      - stack
