version: '3'

volumes:
  mysql:
    driver: ${VOLUMES_DRIVER}

networks:
  stack:
    driver: bridge


services:
  workspace:
    image: mbora/mautic_nginx
    depends_on:
      - php-fpm
      - nginx
    volumes:
      - ${APP_CODE_PATH_HOST}:/var/www
    networks:
      - stack

  nginx:
    image: mbora/mautic_nginx
    depends_on:
      - php-fpm
    ports:
      - "80:80"
    volumes:
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
      - ${APP_CODE_PATH_HOST}:/var/www
    networks:
      - stack
    links:
      - php-fpm

  php-fpm:
    image: mbora/mautic_php-fpm
    networks:
      - stack
    volumes:
      - ${APP_CODE_PATH_HOST}:/var/www



